// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "Windowbuild.h"

/**
 mainwindow
*/
Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(990, 630, "mainwin");
    w = o; if (w) {/* empty */}
    { Fl_Tree* o = new Fl_Tree(10, 40, 200, 350);
      o->color(FL_FOREGROUND_COLOR);
    } // Fl_Tree* o
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 990, 20);
      o->color(FL_LIGHT2);
    } // Fl_Menu_Bar* o
    { new Fl_Button(0, 0, 64, 20, "Load");
    } // Fl_Button* o
    { new Fl_Button(65, 0, 64, 20, "Restart");
    } // Fl_Button* o
    { new Fl_Button(130, 0, 64, 20, "About");
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(240, 60, 730, 565);
      o->box(FL_GTK_DOWN_BOX);
      o->color(FL_LIGHT2);
      o->end();
    } // Fl_Group* o
    { new Fl_File_Browser(10, 400, 200, 300);
    } // Fl_File_Browser* o
    { Fl_Choice* o = new Fl_Choice(290, 35, 125, 20, "choice:");
      o->down_box(FL_BORDER_BOX);
    } // Fl_Choice* o
    o->size_range(500, 1045);
    o->end();
  } // Fl_Double_Window* o
  return w;
}
