// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef belis_h
#define belis_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tree.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_File_Browser.H>
#include <FL/Fl_Choice.H>
#include "FL/Fl.H"
#include "FL/Fl_Button.H"
#include "FL/Fl_Window.H"
#include "FL/Fl_Box.H"
#include "FL/Fl_Input.H"
#include <FL/Fl_Sys_Menu_Bar.H>
#include <FL/Fl_Menu_Item.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Widget.H>
#include <FL/Fl_Tree.H>
#include <FL/Fl_Tree_Item.H>
#include "FL/Fl_Scrollbar.H"
Fl_Double_Window* make_window();
void loadFile();
#endif
